const fs = require('fs').promises
const glob = require('glob')
const path = require('path')
const { log } = require('../utils')

let template = `/**
 * this file is autogenerated, don't touch
 */\n\n`

async function createImports(sourcePath) {
  glob
    .sync(path.resolve(sourcePath, 'components/**/*.component.js'))
    .forEach((file) => {
      let base = path.basename(file, '.component.js')
      template += `import '../components/${base}/${base}.component.js'\n`
    })

  await fs.writeFile(
    path.resolve(sourcePath, 'application', 'components.js'),
    template
  )

  log.message('Autogenerated imports succesful created!')
}

module.exports = { createImports }
